"""Add description field

Revision ID: 1c914ed5374f
Revises: ffa0d09d66f8
Create Date: 2016-09-21 10:49:14.684414

"""

# revision identifiers, used by Alembic.
revision = '1c914ed5374f'
down_revision = 'ffa0d09d66f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'description')
    ### end Alembic commands ###
