"""Added task_uuid to Process

Revision ID: 1d40d3fc3d0c
Revises: ff16bb058061
Create Date: 2016-10-04 10:07:08.038082

"""

# revision identifiers, used by Alembic.
revision = '1d40d3fc3d0c'
down_revision = 'ff16bb058061'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_uuid', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('task_uuid')

    ### end Alembic commands ###
