"""Add Reconstruction model

Revision ID: 7dbb6f237041
Revises: 1d40d3fc3d0c
Create Date: 2016-10-07 11:56:14.711593

"""

# revision identifiers, used by Alembic.
revision = '7dbb6f237041'
down_revision = '1d40d3fc3d0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconstructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flats', sa.String(), nullable=True),
    sa.Column('darks', sa.String(), nullable=True),
    sa.Column('projections', sa.String(), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconstructions')
    ### end Alembic commands ###
