"""Remove explicit parent relationship on Dataset

Revision ID: afb368fbe1ad
Revises: d899f074d6a6
Create Date: 2016-09-28 11:05:00.777820

"""

# revision identifiers, used by Alembic.
revision = 'afb368fbe1ad'
down_revision = 'd899f074d6a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'parent_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'datasets', 'datasets', ['parent_id'], ['id'])
    ### end Alembic commands ###
