"""Add type to notifications

Revision ID: d2dc3ffee522
Revises: f13a99943e85
Create Date: 2017-03-14 15:28:53.584711

"""

# revision identifiers, used by Alembic.
revision = 'd2dc3ffee522'
down_revision = 'f13a99943e85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
