"""Add has_thumbnail to Dataset

Revision ID: d34c125c98cc
Revises: 6867197a0fb9
Create Date: 2016-09-30 14:36:07.835761

"""

# revision identifiers, used by Alembic.
revision = 'd34c125c98cc'
down_revision = '6867197a0fb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_thumbnail', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('has_thumbnail')

    ### end Alembic commands ###
