"""Remove Deletion model

Revision ID: d899f074d6a6
Revises: 5d5b97a64a0c
Create Date: 2016-09-26 15:55:44.269897

"""

# revision identifiers, used by Alembic.
revision = 'd899f074d6a6'
down_revision = '5d5b97a64a0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deletions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('dataset_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
