"""empty message

Revision ID: f13a99943e85
Revises: dc93e5f99ead
Create Date: 2017-01-31 17:25:37.060549

"""

# revision identifiers, used by Alembic.
revision = 'f13a99943e85'
down_revision = 'dc93e5f99ead'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
