"""Add Volume model

Revision ID: ff16bb058061
Revises: d34c125c98cc
Create Date: 2016-09-30 16:35:42.954336

"""

# revision identifiers, used by Alembic.
revision = 'ff16bb058061'
down_revision = 'd34c125c98cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slices', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volumes')
    ### end Alembic commands ###
