"""add first_time to users

Revision ID: ffa0d09d66f8
Revises: 30182fdbaff1
Create Date: 2016-08-05 09:32:47.459220

"""

# revision identifiers, used by Alembic.
revision = 'ffa0d09d66f8'
down_revision = '30182fdbaff1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_time', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_time')
    ### end Alembic commands ###
